apiVersion: v2
name: pagopa-ecommerce-transactions-service
description: Microservice that handles transactions lifecycle and workflow in ecommerce pagoPA
type: application
version: 3.1.2
appVersion: 3.1.2
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
