apiVersion: v2
name: pagopa-ecommerce-transactions-service
description: Microservice that handles transactions lifecycle and workflow in ecommerce pagoPA
type: application
version: 1.30.13
appVersion: 1.30.12
dependencies:
  - name: microservice-chart
    version: 2.3.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
